version: "3.9"
services:
  auth-service:
    image: auth-service
    container_name: auth-service
    ports:
      - "8080:8080"

  storage-service:
    image: storage-service
    container_name: storage-service
    ports:
      - "8081:8081"
      - "9090:9090"

  user-service:
    image: user-service
    container_name: user-service
    ports:
      - "8082:8082"
    depends_on:
      - storage-service